server:
  port: 28080


file:
  upload-path: ${user.dir}
  allowed-types: jpg,png
  max-size: 10485760

spring:

  datasource:
#    url: jdbc:mysql://47.101.159.225:3306/www_abc_com
    url: jdbc:mysql://123.57.146.164:3306/testa # 小组测试用的服务器端数据库地址
    username: fengshenbang
    password: minjie5SON? #根据测试数据库情况更改

    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000




# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

jwt:
  # openssl rand -base64 256
  secret: gx4SN/4gh6QPvLfVWCW8Aoo4l2n66d2338IwXyu1koDT1W94XS35OZJPYkA2IIMMgmlz96LCHSNc8jLYuzwB1IreKOZz2TZhsWODfjHAS9bYlduniCUSuSPZ5/OP15O63fn1kN1N5w64frpyWcWbTtiCgLMkJpnfjmqFMAr7fgcOGyt2rmunvFYni9T78Q4fn/0gpx3qm8zXw3oBbFb1Ge9Wnh1UCSapXd/EzLau3iaXqp9f+8FHmSCo9vbEaRSRMPHdcpnB4WKHKySE/BCNSsWM+kHmHyrAbvKErPCz2XXMnIalUoAtquq03LnmYjrBHyI230VcYEVzGmzLOTsSJw==
  access_token:
    expiration: 3600
  refresh_token:
    expiration: 604800

